### ISSUE TITLE
Order of multiple posts from the same day

### ISSUE THREAD

**Issue by optikfluffel** [BennyHallett/obelisk#16]
Hi, maybe we need to save the time as well, because when you do more than one post per day they come out in an reversed alphabetical order.

![screen shot 2014-12-20 at 00 43 41](https://cloud.githubusercontent.com/assets/379915/5512754/75a85f9c-87e1-11e4-880c-b1f7f63575ef.png)

**Comment by optikfluffel** [comment]
What is your opinion on how to handle this issue, would it be better to change all the filenames to include the time or just add it to the front matter on top of the file and go from there?

**Comment by BennyHallett** [comment]
I feel like the front-matter makes more sense. It might be pretty ugly having both the time and date in the filename.

I also like the idea of removing the date stamp from the filename all together.

**Comment by optikfluffel** [comment]
Would be nice to get rid of the date stamp, but then we would need something like a folder structure to keep the posts organised, something like `posts`/`year`/`month`/`title.markdown`

**Comment by BennyHallett** [comment]
Yeah I agree, I also like the idea of keeping the filenames as they are and using the front matter for ordering.

**Comment by BennyHallett** [comment]
This issue has now been resolved. It'll be included in the next release (not sure when that will be but it wont be long)
