### ISSUE TITLE
100% CPU when serving

### ISSUE THREAD

**Issue by AdamBrodzinski** [BennyHallett/obelisk#28]
When I run `blog|⇒ mix obelisk server` my CPU is pegged at 100%. Is this a known issue? Are there any work arounds?

**Comment by BennyHallett** [comment]
I suspect it's this busy-loop when waiting for the cowboy server to die:

https://github.com/BennyHallett/obelisk/blob/master/lib/obelisk/tasks/server.ex#L21

I haven't done any work on Obelisk in quite a while but intend to fix some issues starting next week. i'll clean this one up then.

**Comment by AdamBrodzinski** [comment]
@BennyHallett ah, sounds good! I would checkout this fork. I think Clark fixed this and the titles that were not working:
https://github.com/ckampfe/obelisk

**Comment by mvalitov** [comment]
Hi, I'm seeing the same problem, 

> When I run blog|⇒ mix obelisk server my CPU is pegged at 100%

I'm using the version
```
    [{ :obelisk, "~> 0.10.0" },
   {:yamerl, "~> 0.4.0"}]
```

You have no idea how to fix it? Thanks
