### ISSUE TITLE
yamerl doesn't compile on windows

### ISSUE THREAD

**Issue by immigrantsheep** [BennyHallett/obelisk#38]
Unable to install obelisk on windows because yamerl compiling fails with the message:

==> yamerl (compile)
ERROR: sh(cmd /q /c awk '/^AC_INIT(/ { ver=; sub(/AC_INIT([[^]]+], _[/, "", ver); sub(/]._/, "", ver); print ver; } { next; }' configure.ac)
failed with return code 1 and the following output:
awk: cmd. line:1: /AC_INIT(/ { ver=; sub(/AC_INIT([[]]+], _[/, "", ver); sub(/]._/, "", ver); print ver; } { next; }
awk: cmd. line:1:                   ^ syntax error

**Comment by BennyHallett** [comment]
Hey @immigrantsheep - Sorry I've been slack with Obelisk and haven't addressed your issue.

Unfortunately I have no access to a Windows machine so will be unlikely to resolve this by hunting it down myself. I will however be upgrading Obelisk in the coming weeks so hopefully pulling in later versions of yamerl might fix the issue.

**Comment by immigrantsheep** [comment]
Thank you for your reply :) I'll check it out again once you update it and in the meantime I'll close this down. Cheers!
